name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: eigenmath-linux
          path: ./eigenmath

  build-macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: eigenmath-macos
          path: ./eigenmath

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: eigenmath-windows
          path: ./eigenmath.exe
